# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'popularmovies2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SDWebImage', '~> 4.0'
pod 'AFNetworking', '~> 3.0'
pod 'Alamofire', '~>4.6'
pod 'Dropdowns'
pod 'WCLShineButton'
pod 'Cosmos'
end
